name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        #os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          # CI before build install go as its a dependency
          CIBW_BEFORE_BUILD: "curl -O https://go.dev/dl/go1.21.13.linux-amd64.tar.gz && \ tar -xvf go1.21.13.linux-amd64.tar.gz && \ mv go /usr/local "