name: PR Check

on: [push, pull_request]

jobs:
  build_wheels:
    name: Check PR for formatting, secrets, and other requirements 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure we have python
      - uses: actions/setup-python@v5
      # Pull in ruff and detect secrets for PR checks
      - uses: astral-sh/ruff-action@v3
      - name: Install detect secrets
        run: python -m pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
      - name: Run check
        run: make check